### ISSUE TITLE
How do you handle builds with dependencies?

### ISSUE THREAD

**Issue by pzybe** [lambci/awslambda.nim#1]
Is there any good methods for overcoming the Amazon Linux AMI's extremely old environment?  Right now I find that I can't really do too many meaningful things with awslambda in Nim because of it. A few examples of the pitfalls I've run into:

If i try to dynamically link everything, and upload the binary along with .so files, and overwrite the library path for lambda, I run into the issue of the AMZN Linux AMI's GLIBC version being from 2012.  Aspects of GLIBC keep one from tossing it around in compressed archives (hardcoded paths).

If I try to use something like nimcrypto, which has openssl as a dependency, I run into the fact that if I supply my own openssl binaries, they do not work with the AMI's version of GLIBC.  If I let it default to the system's openssl libraries, they're again way too old for nimcrypto to use.

If I want to package my own glibc, I have to go through the precarious steps of having two versions of glibc on my system, and I have to build it anticipating the paths it will reside with.

If I want to statically link my binary, I'd have to use something like musl, and i'd have to cross-compile openssl with musl.

I guess I could go with static linking with musl using my own build version of openssl but this feels like I'm losing the magic at this point.

Would be helpful if there were some examples of building a Nim lambda that packaged it's own dynamically linked libs, or some statically linked approach, etc.

**Comment by mhart** [comment]
The recommended approach now would be to use [yumda](https://github.com/lambci/yumda) to install any missing libraries you need and then publish them as a layer (or include them with your custom runtime)
