### ISSUE TITLE
Is this still a viable library?

### ISSUE THREAD

**Issue by OldhamMade** [lambci/awslambda.nim#2]
I've followed the instructions using Nim v1.0.2 and v0.19.6 and I'm unable to get a success from a test on Lambda. I'm seeing the following:

![Screenshot 2019-11-21 12 51 29](https://user-images.githubusercontent.com/111193/69335840-d992f480-0c5d-11ea-9409-a06bd072f0cd.png)

I've confirmed the lambda "test" works on AWS by using Crystal & [crambda](https://github.com/lambci/crambda), but I wanted to compare Nim v1.0.X startup/execution time against Crystal's.

Any assistance you can provide would be wonderful!

**Comment by mhart** [comment]
It looks like you don't have the compiled `bootstrap` file at the root of the zip you uploaded to Lambda. What is the contents of your zip? Try `unzip -l` to see

**Comment by OldhamMade** [comment]
@mhart It's odd, as it does look like it's there:

```bash
$ unzip -l lambda.zip
Archive:  lambda.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   273880  11-21-2019 16:49   bootstrap
---------                     -------
   273880                     1 file
```

<img width="880" alt="Screenshot 2019-11-21 at 17 05 25" src="https://user-images.githubusercontent.com/111193/69354871-1e7c5280-0c81-11ea-9e3d-a420b71a8555.png">

**Comment by OldhamMade** [comment]
BTW, a Crystal file with the same name in the same location works fine. Is there a minimum binary size required, perhaps?

**Comment by mhart** [comment]
Hang on, that looks like a different error

**Comment by mhart** [comment]
Can you post the text of that error? The first error was that it couldn't find bootstrap – this error looks different

**Comment by OldhamMade** [comment]
Apologies, that screenshot was for nim v1.0.2.

Here's the output when using nim v0.19.6:

```
Response:
{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: 7fd899a9-c45f-4a65-be09-76e7ccfbaf49 Error: &{0xc00005c2a0 map[invoke_id:7fd899a9-c45f-4a65-be09-76e7ccfbaf49 sandbox_id:0] 2019-11-21 17:02:11.286216291 +0000 UTC m=+0.015047762 panic <nil> Runtime failed to start: fork/exec /var/task/bootstrap: no such file or directory <nil> }"
}

Request ID:
"7fd899a9-c45f-4a65-be09-76e7ccfbaf49"

Function Logs:
START RequestId: 7fd899a9-c45f-4a65-be09-76e7ccfbaf49 Version: $LATEST
END RequestId: 7fd899a9-c45f-4a65-be09-76e7ccfbaf49
REPORT RequestId: 7fd899a9-c45f-4a65-be09-76e7ccfbaf49	Duration: 35.31 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 12 MB	
RequestId: 7fd899a9-c45f-4a65-be09-76e7ccfbaf49 Error: &{0xc00005c2a0 map[invoke_id:7fd899a9-c45f-4a65-be09-76e7ccfbaf49 sandbox_id:0] 2019-11-21 17:02:11.286216291 +0000 UTC m=+0.015047762 panic <nil> Runtime failed to start: fork/exec /var/task/bootstrap: no such file or directory <nil> }
Runtime.ExitError
```

**Comment by mhart** [comment]
You're using exactly the example from the README? And compiling it using Docker?

It all works for me:

```console
$ docker run --rm -v "$PWD":/app -w /app nimlang/nim \
  sh -c 'nimble install -y awslambda && nim c -d:release bootstrap.nim'

Status: Downloaded newer image for nimlang/nim:latest
    Prompt: No local packages.json found, download it from internet? -> [forced yes]
Downloading Official package list
    Success Package list downloaded.
Downloading https://github.com/lambci/awslambda.nim using git
  Verifying dependencies for awslambda@0.2.0
 Installing awslambda@0.2.0
   Success: awslambda installed successfully.
Hint: used config file '/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: bootstrap [Processing]
...
CC: bootstrap.nim
Hint:  [Link]
Hint: operation successful (85020 lines compiled; 6.347 sec total; 89.73MiB peakmem; Release Build) [SuccessX]
```
And then:
```console
zip -yr lambda.zip bootstrap
```

**Comment by OldhamMade** [comment]
Nearly the same. Building in docker but instead of `nim c -d:release bootstrap.nim` I'm using `nimble release`, with a nimble task that is essentially the same:
```
task release, "Build a release":
  --verbose
  --define:release
  --outdir:"."
  setCommand "c", "src/bootstrap.nim"
```

But I've found the issue: I'd used `nimlang/nim:alpine` which is obviously invalid. I really shouldn't code before my first coffee of the day kicks in!

Building with the nimble task, using `nimlang/nim`, I get a successful build:

<img width="846" alt="Screenshot 2019-11-21 18 19 29" src="https://user-images.githubusercontent.com/111193/69360844-93548a00-0c8b-11ea-8194-eab629bc24b4.png">

Really sorry to bother you with this.

**Comment by mhart** [comment]
Awesome, glad you found the issue 👍 

Nim is *super* fast – like, the fastest runtime I've tested. I'd be interested to hear how you go with it!
